set -e
true
true
/usr/libexec/spades/spades-hammer /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/corrected/configs/config.info
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/compress_all.py --input_file /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/corrected/corrected.yaml --ext_python_modules_home /usr/share/spades --max_threads 16 --output_dir /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/corrected --gzip_output
true
true
/usr/libexec/spades/spades-core /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K21/configs/config.info
/usr/libexec/spades/spades-core /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K33/configs/config.info
/usr/libexec/spades/spades-core /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K55/configs/config.info
/usr/libexec/spades/spades-core /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/configs/config.info
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/copy_files.py /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/before_rr.fasta /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/before_rr.fasta /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/assembly_graph_after_simplification.gfa /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/assembly_graph_after_simplification.gfa /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/final_contigs.fasta /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/contigs.fasta /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/first_pe_contigs.fasta /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/first_pe_contigs.fasta /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/strain_graph.gfa /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/strain_graph.gfa /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/scaffolds.fasta /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/scaffolds.fasta /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/scaffolds.paths /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/scaffolds.paths /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/assembly_graph_with_scaffolds.gfa /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/assembly_graph_with_scaffolds.gfa /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/assembly_graph.fastg /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/assembly_graph.fastg /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/K77/final_contigs.paths /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/contigs.paths
true
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/scaffolds.fasta --misc_dir /workspaces/100_days/ecoli_genome_annotation/ecoli_genome_project/assembly/misc --threshold_for_breaking_scaffolds 3
true
